services:
  untitled-card-game:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-prod}
      args:
        SERVER_URL: ${SERVER_URL}
    container_name: untitled-card-game-client
    volumes:
      - .:/app
      - node-modules:/app/node_modules
      - pnpm-store:/app/.pnpm-store/v3
    environment:
      SERVER_URL: ${SERVER_URL}
      PORT: ${PORT:-5173}
    ports:
      - '${PORT:-5173}:${PORT:-5173}'
    networks:
      - ucg_network

networks:
  ucg_network:
    external: true

volumes:
  node-modules:
  pnpm-store:
