name: Build API

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'libs/shared/**'
  push:
    branches:
      - main
      - ci/**
    paths:
      - 'apps/api/**'
      - 'libs/shared/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.23'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build API
        run: cd apps/api && bun run build

      - name: Debug - Check build output
        run: |
          echo "Contents of apps/api:"
          ls -la apps/api/
          echo "Checking for dist directory:"
          ls -la apps/api/dist/ || echo "dist directory not found"

      - name: Notify on failure
        if: failure()
        run: |
          echo "Deployment failed! Check the logs."
          # Add Slack/Discord notification here if needed
