name: Publish Package to NPM

on:
  pull_request:
    types: [closed]
    paths:
      - 'shared/**'
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shared

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if version changed
        id: version_check
        run: |
          git fetch origin main --depth=1
          if git diff --name-only origin/main ${{ github.sha }} | grep 'package.json'; then
            if git diff origin/main ${{ github.sha }} -- package.json | grep '"version"'; then
              echo "changed=true" >> "$GITHUB_OUTPUT"
            else
              echo "changed=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Enable Corepack and latest pnpm
        if: steps.version_check.outputs.changed == 'true'
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        if: steps.version_check.outputs.changed == 'true'
        run: pnpm install --frozen-lockfile

      - name: Build package
        if: steps.version_check.outputs.changed == 'true'
        run: pnpm build

      - name: Publish to NPM
        if: steps.version_check.outputs.changed == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
